# Site settings
title: UoPCS - University of Portsmouth Computing Society
description: The Computing Society is a place to hang out with people with a passion for computing. We hold socials as well as organised talks and group projects throughout the year.

# social media

twitter: uopcs
facebook: uopcs
github: uopcs

signup: http://www.upsu.net/activities/societies/a-z-societies/computing.php

# build settings
markdown: kramdown
